### Task 1

### Write a function to compute 5/0 and use try/except to catch the exceptions.

In [2]:
def divide(x, y):
    try:
        result = x / y
        print(result)
    except ZeroDivisionError:
        print("Sorry ! Division by zero is not allowed. ")
        
print("The result of dividing 7 by 5 is : ")
divide(7,5)
print("The result of dividing 5 by 0 is : ")
divide(5,0)

The result of dividing 7 by 5 is : 
1.4
The result of dividing 5 by 0 is : 
Sorry ! Division by zero is not allowed. 


### Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

In [11]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

result_list = [(subject+" "+verb+" "+obj+".") for subject in subjects for verb in verbs for obj in objects]
for item in result_list : 
    print(item)

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


### Task 2

### Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [25]:
import numpy as np
x = np.array([14,67,34,90]) #input vector
N = 4 
print("The Vandermonde matrix(with increasing=False), generated for given vector is :")
print(np.column_stack([x**(N-1-i) for i in range(N)]))
print("The Vandermonde matrix(with increasing=True), generated for given vector is :")
print(np.vander(x, increasing=True))

The Vandermonde matrix(with increasing=False), generated for given vector is :
[[  2744    196     14      1]
 [300763   4489     67      1]
 [ 39304   1156     34      1]
 [729000   8100     90      1]]
The Vandermonde matrix(with increasing=True), generated for given vector is :
[[     1     14    196   2744]
 [     1     67   4489 300763]
 [     1     34   1156  39304]
 [     1     90   8100 729000]]
